<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv='Content-type' content='text/html; charset=ISO-8859-1' />
<title></title>
<?= javascript_include_tag('jquery/jquery-1[1][1].2.1') ?>
<?= kumbia::javascript_base() ?>
<?= stylesheet_link_tag('style', true) ?>
<?= stylesheet_link_tag('login') ?>
<?= kumbia::stylesheet_link_tags() ?>
</head>
<body>
<div id="container">
    <div id="content">
            <?= form_tag("config/index", 'name: login') ?>
			<form name="frmLogin" method="post" action="">
			    <table class="adminLoginTable" cellpadding="0" cellspacing="0">
			        <thead>
			            <tr>
			                <th colspan="2">SOLO PARA USUARIOS</th>
			            </tr>
			        </thead>
			        <tbody>
			            <tr>
			                <th class="padTop"><label>Usuario: </label></th>
			                <td class="padTop"><input type="text" value="" class="input" name="username" id="username" /></td>
			            </tr>
			            <tr>
			                <th><label>Password: </label></th>
			                <td><input type="password" value="" class="input" name="password" id="password" /></td>
			            </tr>
			        </tbody>
			        <tfoot>
			            <tr>
			            	<td>&nbsp;</td>
			              <td><input type="submit" class="button" value="Login" /></td>
			            </tr>
			        </tfoot>
			    </table>
			<?= end_form_tag() ?>
    </div>
</div>
</body>
</html>
