<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv='Content-type' content="text/html; charset=UTF-8" />
<title></title>
<?= kumbia::javascript_base() ?>
<?= stylesheet_link_tag('css/style', true) ?>
</head>
<body>

	<?= form_tag("config/index", 'name: login','id: login-form') ?>
		<fieldset>

			<legend>Irraco</legend>

			<label for="login">Email</label>
			<input type="text" id="login" name="login"/>
			<div class="clear"></div>

			<label for="password">Password</label>
			<input type="password" id="password" name="password"/>
			<div class="clear"></div>

			<label for="remember_me" style="padding: 0;">Recuerdame?</label>
			<input type="checkbox" id="remember_me" style="position: relative; top: 3px; margin: 0; " name="remember_me"/>
			<div class="clear"></div>

			<br />

			<input type="submit" style="margin: -20px 0 0 287px;" class="button" name="commit" value="OK"/>
		</fieldset>
	<?= end_form_tag() ?>

</body>
</html>
