<table align="center">
<tr><td><center><h2>-----------------------********************-----------------------</h2></center></td></tr>
         <tr>
         <td align="center" class="bg1" height="500px" width="1064px">
         <h2>INSTALACI&Oacute;N DE NUEVOS M&Oacute;DULOS</h2><br />
         <div id="msn"><?= file_field_tag('module','size: 75') ?>
         <input type="Button" onclick="show(get_kumbia_url(''),'msn','html');" id="install" value="Instalar"></div>
         </td>
         </tr>
<tr><td><center><h2>-----------------------********************-----------------------</h2></center></td></tr>         
</table>
