<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=ISO-8859-1' />
  <title>Configuraci&oacute;n del S&iacute;stema</title>
  <?= javascript_include_tag('jquery/jquery-1[1][1].2.1') ?>
  <?= kumbia::javascript_base() ?>
  <? stylesheet_link_tag('style', true) ?>
  <?= kumbia::stylesheet_link_tags() ?> 
 </head>
 <body>
<br />  <br />
<?php content() ?>
<table class="bg1" border="1">
    <tr>
		<td colspan="100%" align="center">
        <h1><u>Listado de M&oacute;dulos</u></h1>
		</td>
    </tr>
<? foreach($inferior as $campo){ ?>
	<tr>
		<td><? print $campo->nombre; ?></td>
		<td><? print $campo->descripcion ?></td>
		<td><? print $campo->fecha_at ?></td>
		<td><? print $campo->fecha_in ?></td>
		<td><?=img_tag($campo->image,"heigth: 32", "width: 32")?></td>
		<td><? print $campo->autores ?></td>
		<td bgcolor="#AABCCE"><?= link_to("modulos/modificar/{$campo->id}","Modulo") ?></td>
		<td bgcolor="#AABCCE"><?= link_to("modulos/listadescripcion/{$campo->id}","Descripcion") ?></td>
	</tr>
<? } ?>	
	<tr>
		<td colspan="100%" align="center">		
			 <?= link_to('config/index', 'volver Principal') ?>
		</td>
	</tr>
</table>
<br /> <br />
</body>
</html>