<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=ISO-8859-1' />
  <title>Configuraci&oacute;n del S&iacute;stema</title>
  <?= javascript_include_tag('jquery/jquery-1[1][1].2.1') ?>
  <?= kumbia::javascript_base() ?>
  <? stylesheet_link_tag('style', true) ?>
  <?= stylesheet_link_tag('login') ?>
  <?= kumbia::stylesheet_link_tags() ?> 
 </head>
 <body>
<br />  <br />
<?php content() ?>
<?= form_tag("modulos/modifica_descripcion/$id", 'name: modi') ?>
<table class="adminLoginTable" cellpadding="0" cellspacing="0">
    <thead>
    <tr>
		<th colspan="2" align="center">
        <h3>Modificar: <?php print $elementos->nombret ?></h3>
		</th>
    </tr>
    </thead>
    <tbody>
	<tr>
	    <td>Nombre o Pseudonimo de la Tabla:</td>
		<td><?= text_field_tag('nombre',"value: {$elementos->nombret}","size: 60") ?></td>
	</tr>
	<tr>
	    <td>Nombre o Pseudonimo del campo:</td>                       
		<td><?= text_field_tag('campo',"value: {$elementos->campot}","size: 35") ?></td>
	</tr>
    <tr>	
		<td>Descripcion:</td>
		<td><?= textarea_tag("value: $elementos->descripcion",'name: desc','cols: 40','rows: 5') ?></td>
	</tr> 
    </tbody> 
    <tfoot>  
	<tr>		
		<td colspan="100%" align="center">
			 <?= submit_tag('Modificar', "class: button") ?><br />
			 <?= link_to('config/index', 'volver Principal') ?>
		</td>                       
	</tr>
	</tfoot>
</table>
<?= end_form_tag() ?> 
<br /> <br />
</body>
</html>